"""Add address column to person abstract model

Revision ID: 04b1c056ade2
Revises: ba73114ea52e
Create Date: 2020-02-09 22:21:37.301107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b1c056ade2'
down_revision = 'ba73114ea52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
