"""Added image_file_name to store profile pic path

Revision ID: 16588d4b7aba
Revises: 76475e1d18e0
Create Date: 2020-04-23 22:53:52.078180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16588d4b7aba'
down_revision = '76475e1d18e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file_name', sa.String(length=128), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('image_file_name')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('image_file_name')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###
