"""Added is_active boolean property for User table with default set to true

Revision ID: 17409fbc1c6e
Revises: 02a116b9cb2b
Create Date: 2020-01-13 22:25:17.475561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17409fbc1c6e'
down_revision = '02a116b9cb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
