"""Removed ScoreType table

Revision ID: 2036141a3ac3
Revises: 98a17781180d
Create Date: 2020-02-27 08:05:10.237633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2036141a3ac3'
down_revision = '98a17781180d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_type', schema=None) as batch_op:
        batch_op.drop_index('ix_score_type_score_type')

    op.drop_table('score_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('score_type', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_type', schema=None) as batch_op:
        batch_op.create_index('ix_score_type_score_type', ['score_type'], unique=1)

    # ### end Alembic commands ###
