"""Added serial_number column to Person model

Revision ID: 4a6eab12fba0
Revises: 17409fbc1c6e
Create Date: 2020-01-22 22:15:38.085529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6eab12fba0'
down_revision = '17409fbc1c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom') as classroom_op:
        classroom_op.alter_column('classroom_name',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=False)
        classroom_op.alter_column('classroom_symbol',
                   existing_type=sa.VARCHAR(length=8),
                   nullable=False)
        # op.create_index(op.f('ix_classroom_classroom_symbol'), 'classroom', ['classroom_symbol'], unique=True)
    with op.batch_alter_table('staff') as staff_op:
        staff_op.add_column(sa.Column('serial_number', sa.String(length=32), nullable=False))
        staff_op.create_unique_constraint('staff', ['serial_number'])
    with op.batch_alter_table('student') as student_op:
        student_op.add_column(sa.Column('serial_number', sa.String(length=32), nullable=False))
        student_op.create_unique_constraint('student', ['serial_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'serial_number')
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('staff', 'serial_number')
    op.drop_index(op.f('ix_classroom_classroom_symbol'), table_name='classroom')
    op.alter_column('classroom', 'classroom_symbol',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('classroom', 'classroom_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
