"""Made the current_session field property to False

Revision ID: 5742a8cfad69
Revises: 2c94aaf46222
Create Date: 2020-03-10 22:48:09.696843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5742a8cfad69'
down_revision = '2c94aaf46222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('current_session',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('current_session',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
