"""Dropped SchoolSession table

Revision ID: 76475e1d18e0
Revises: d6c7badb0a42
Create Date: 2020-03-14 14:54:59.849506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76475e1d18e0'
down_revision = 'd6c7badb0a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_session', schema=None) as batch_op:
        batch_op.drop_index('ix_school_session_session')

    op.drop_table('school_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session', sa.VARCHAR(length=32), nullable=True),
    sa.Column('current_session', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.CheckConstraint('current_session IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_session', schema=None) as batch_op:
        batch_op.create_index('ix_school_session_session', ['session'], unique=1)

    # ### end Alembic commands ###
