"""Removed index property on current_session field in Sessions table

Revision ID: 82d963964460
Revises: 9383ada2cbf6
Create Date: 2020-03-12 22:11:07.809466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d963964460'
down_revision = '9383ada2cbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_current_session')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_current_session', ['current_session'], unique=False)

    # ### end Alembic commands ###
