"""Added StudentResults model to store results for student scores

Revision ID: 91b7193a1f8c
Revises: 2036141a3ac3
Create Date: 2020-02-27 22:21:13.380292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b7193a1f8c'
down_revision = '2036141a3ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=False),
    sa.Column('sessions_id', sa.Integer(), nullable=False),
    sa.Column('ca_score', sa.Integer(), nullable=False),
    sa.Column('exam_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=8), nullable=True),
    sa.Column('grade_remark', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['sessions_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_results')
    # ### end Alembic commands ###
