"""Made current_session field in Sessions table not nullable

Revision ID: 9383ada2cbf6
Revises: fc08eff82f6f
Create Date: 2020-03-12 08:55:12.982383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9383ada2cbf6'
down_revision = 'fc08eff82f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('current_session',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('current_session',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
