"""Added ScoreType table

Revision ID: 98a17781180d
Revises: 6a163bafffe9
Create Date: 2020-02-20 22:31:41.432826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a17781180d'
down_revision = '6a163bafffe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_type_score_type'), ['score_type'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_type_score_type'))

    op.drop_table('score_type')
    # ### end Alembic commands ###
