"""Added tables for staff and student using abstract table, added classroom table and defined 1-many relationship with classroom and student

Revision ID: b3f457ffd949
Revises: 6d0584c8cb14
Create Date: 2020-01-08 22:26:44.360302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f457ffd949'
down_revision = '6d0584c8cb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_name', sa.String(length=128), nullable=True),
    sa.Column('classroom_symbol', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('middlename', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('contact_number', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('student',
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('middlename', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('contact_number', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_guardian_name', sa.String(length=128), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('staff')
    op.drop_table('classroom')
    # ### end Alembic commands ###
