"""Added SchoolSession model

Revision ID: d6c7badb0a42
Revises: 82d963964460
Create Date: 2020-03-12 22:27:33.550092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c7badb0a42'
down_revision = '82d963964460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(length=32), nullable=True),
    sa.Column('current_session', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_session_session'), ['session'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_session_session'))

    op.drop_table('school_session')
    # ### end Alembic commands ###
