"""Made the current_session nullable

Revision ID: fc08eff82f6f
Revises: 5742a8cfad69
Create Date: 2020-03-10 22:57:58.722017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc08eff82f6f'
down_revision = '5742a8cfad69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('current_session',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('current_session',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
